//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class demo
    {
        public int Srno { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
        public string EmailId { get; set; }
        public string ReportingTo { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string JoinDate { get; set; }
        public string UserRole { get; set; }
    }
}
