//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class excel4
    {
        public int SerialNo { get; set; }
        public string Date { get; set; }
        public string Day { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public string Shift { get; set; }
        public string ScheduledInTime { get; set; }
        public string ScheduledOutTime { get; set; }
        public string ActualTimeIn { get; set; }
        public string ActualTimeOut { get; set; }
        public string WorkDuration { get; set; }
        public string OverTime { get; set; }
        public string TimeDuration { get; set; }
        public string LateBy { get; set; }
        public string EarlyGoingBy { get; set; }
        public string Status { get; set; }
    }
}
