//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class excel5
    {
        public string Srno { get; set; }
        public string Date { get; set; }
        public string Day { get; set; }
        public string ScheduledInTime { get; set; }
        public string ScheduledOutTime { get; set; }
        public string LateBy { get; set; }
        public string ReasonOfLeave { get; set; }
    }
}
